#!/bin/bash

# Include guard
if [ -z "$DOTFILES" ]; then
    export DOTFILES=yes
else
    return 0
fi

# Operating system specific settings
if [[ "$OSTYPE" == "linux-gnu" ]]; then
	# Linux
    :

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OS X
 
	# Highlight items
	export CLICOLOR=1
	export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
	#export LSCOLORS=GxFxCxDxBxegedabagaced

else
    echo "Unrecognized operating system"
fi

# Settings that depend on whether or not the session is over SSH
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
    # Using SSH
    :

else
    # Not using SSH

    # Shorten prompt
    PS1='\u: \W$ '
fi

# git prompt
# https://github.com/magicmonty/bash-git-prompt
export PROMPT_COMMAND=""
GIT_PROMPT_ONLY_IN_REPO=1
source ~/dotfiles/bash-git-prompt/gitprompt.sh

# deprecated git prompt
#source ~/.git-prompt.sh
#PS1='\u: \W$(__git_ps1 " (%s)")\$ '

# Git listing of branches by date
alias glist='for ref in $(git for-each-ref --sort=-committerdate --format="%(refname)" refs/heads/ refs/remotes ); do git log -n1 $ref --pretty=format:"%Cgreen%cr%Creset %C(yellow)%d%Creset %C(bold blue)<%an>%Creset%n" | cat ; done | awk '"'! a["'$0'"]++'"

# Don't put duplicate lines in the history.
HISTCONTROL=ignoredups

# Append and combine history from multiple bash sessions.
# This section must come after the git prompt section because it overrides the PROMPT_COMMAND.
unset HISTFILESIZE
export HISTSIZE=10000
export PROMPT_COMMAND="$PROMPT_COMMAND;history -a;"
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Disable Ctrl-D to logout of a shell session
set -o ignoreeof

# Re-enable Ctrl-S to forward search commands in the shell
stty -ixon
